services:
  memory_api:
    build: ./Dockerfile
    ports:
      - "3000:3000"
  memory_db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - memory_db:/var/lib/mysql
volumes:
  memory_db:
